### ISSUE TITLE
Using WIF's SAM Cookies in ASP.NET Core

### ISSUE THREAD

**Issue by RDalziel** [blowdart/idunno.CookieSharing#14]
Bit of an old repository but not sure where else to ask!

I'm looking to start migrating some old ASP.NET Framework OWIN APIs over to ASP.NET Core. One of the issues i'm having is what seems to be a lack of port for the System.IdentityModel libraries. Specifically around the Session Authentication Module referenced here :
https://brockallen.com/2013/01/26/replacing-forms-authentication-with-wifs-session-authentication-module-sam-to-enable-claims-aware-identity/

Is there any guidance on how to read .fedAuth Cookies and pull out their claims in ASP.NET Core? In my case - we have a fairly rubbish Machine Key encryption (System.IdentityModel.Services.Tokens.MachineKeySessionSecurityTokenHandler) so i can't imagine it'd be too difficult. I'd hoped someone had already created something on this but i can't seem to find anything anywhere!

**Comment by blowdart** [comment]
Machine key doesn't exist in core. There's no supported way to do this. Plus, as Core supports WS-Fed and OIDC you should just be authenticating in Core itself, rather than try to share.

**Comment by RDalziel** [comment]
That's the intention - we are in the process of moving out Auth Server over to Identity Server but it's a very slow process. This is an intermediate query to get us moving onto .NET Core without having to wait for the modern auth.

**Comment by blowdart** [comment]
You can bind auth to ADFS or use the WS-Fed module in place of WIF until you get Identity Server in place. I'd bite the bullet and do that temporary step rather than try to use reflector or anything else to try to decompile the bits you'd need. It'd be quicker :)

**Comment by RDalziel** [comment]
Hah - i'm not as confident as you that i could make this on the Auth Server without breaking other Apps. Was hoping i could isolate the fix at the App i'm looking to get into the wonderful world of .NET Core. (And it is...wonderful...!)
