### ISSUE TITLE
How to store data protection provider in database without using DirectoryInfo 

### ISSUE THREAD

**Issue by NhatDuy1407** [blowdart/idunno.CookieSharing#4]
Hello @blowdart ,

Your sample demo is very useful. But I need to store **data protection provider** in **database** without using **DirectoryInfo** as below:
`string contentRoot = env.ContentRootPath;`
`string keyRingPath = Path.GetFullPath(Path.Combine(contentRoot, "..", "idunno.KeyRing"));`
`// Now we create a data protector, with a fixed purpose and sub-purpose used in key derivation.`
`var protectionProvider = DataProtectionProvider.Create(new DirectoryInfo(keyRingPath));`
`var dataProtector = protectionProvider.CreateProtector(`
`"Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware",`
`"Cookie",`
`"v2");`
`var ticketFormat = new TicketDataFormat(dataProtector);`

Could you please give me some idea about this?

Thanks in advance.

**Comment by blowdart** [comment]
That's a question for the data protection repo, not here. It's easy enough though, you write your own, implementing IXmlRepository according to your schema and table layouts.

**Comment by NhatDuy1407** [comment]
Many Thanks. 
Because of your hint "IXmlRepository", I could "store data protection provider in database without using DirectoryInfo".
