### ISSUE TITLE
How to configure cookie sharing with a Sharepoint 4.5 web site and asp.net core application

### ISSUE THREAD

**Issue by TheTechArch** [blowdart/idunno.CookieSharing#5]
@blowdart  Thanks for your example.  

In our plattform we have different sites today running formsauthentication sharing the cookie so users can navigate between sites without any issues. 

We want to add a new site to the plattform running asp.net core and we can use your approach for the MVC 5 site.

But we have also a SharePoint 2013 Web site running FormsAuthentication.

Is it possible to share authentication Cookies between a SharePoint site and a asp.net core application?
How can this be set up? There is no startup.cs in this kind of site and machinekey is shared throug web.config amongst the applications/web sites.

**Comment by blowdart** [comment]
Nope, webforms & sharepoint use older tech for this, and you simply can't do it.
